"""Shared runtime action metadata registry.

This registry centralizes the semantics that were previously spread across
the harness registry and downstream script consumers. The implementation is
fail-closed: unknown actions fall back to conservative defaults.
"""

from __future__ import annotations

from dataclasses import dataclass, replace


@dataclass(frozen=True)
class ActionSpec:
    name: str
    script_name: str
    category: str = 'general'
    read_only: bool = False
    concurrent_safe: bool = False
    timeout_s: int = 15
    max_output_chars: int = 5000
    risk_action: str = 'write-state'
    target_type: str = 'state'
    evidence_policy: str = 'basic'
    progress_policy: str = 'standard'
    degradation_class: str = 'default'
    needs_validation: bool = True
    can_modify_state: bool = True


DEFAULT_ACTION_SPEC = ActionSpec(
    name='unknown',
    script_name='unknown',
)


def normalize_action_name(script_name: str) -> str:
    return script_name.replace('.py', '').split('/')[-1].split('\\')[-1]


def _spec(
    name: str,
    *,
    category: str = 'general',
    read_only: bool = False,
    concurrent_safe: bool = False,
    timeout_s: int = 15,
    max_output_chars: int = 5000,
    risk_action: str = 'write-state',
    target_type: str = 'state',
    evidence_policy: str = 'basic',
    progress_policy: str = 'standard',
    degradation_class: str = 'default',
    needs_validation: bool = True,
    can_modify_state: bool = True,
) -> ActionSpec:
    return ActionSpec(
        name=name,
        script_name=name,
        category=category,
        read_only=read_only,
        concurrent_safe=concurrent_safe,
        timeout_s=timeout_s,
        max_output_chars=max_output_chars,
        risk_action=risk_action,
        target_type=target_type,
        evidence_policy=evidence_policy,
        progress_policy=progress_policy,
        degradation_class=degradation_class,
        needs_validation=needs_validation,
        can_modify_state=can_modify_state,
    )


ACTION_SPECS: dict[str, ActionSpec] = {
    'render_state_views': _spec(
        'render_state_views',
        category='reporting',
        read_only=True,
        concurrent_safe=True,
        timeout_s=30,
        max_output_chars=10000,
        risk_action='read',
        target_type='report',
        evidence_policy='none',
        progress_policy='none',
        degradation_class='read_only',
        needs_validation=False,
        can_modify_state=False,
    ),
    'build_next_task_from_state': _spec(
        'build_next_task_from_state',
        category='scheduling',
        read_only=True,
        concurrent_safe=True,
        timeout_s=15,
        risk_action='read',
        target_type='state',
        evidence_policy='state',
        progress_policy='derived',
        degradation_class='read_only',
        needs_validation=False,
        can_modify_state=False,
    ),
    'build_heartbeat_summary': _spec(
        'build_heartbeat_summary',
        category='reporting',
        read_only=True,
        concurrent_safe=True,
        timeout_s=15,
        risk_action='read',
        target_type='report',
        evidence_policy='heartbeat',
        progress_policy='none',
        degradation_class='read_only',
        needs_validation=False,
        can_modify_state=False,
    ),
    'build_resume_state': _spec(
        'build_resume_state',
        category='resume',
        read_only=True,
        concurrent_safe=True,
        timeout_s=30,
        max_output_chars=10000,
        risk_action='read',
        target_type='state',
        evidence_policy='resume',
        progress_policy='derived',
        degradation_class='read_only',
        needs_validation=False,
        can_modify_state=False,
    ),
    'build_observability_dashboard': _spec(
        'build_observability_dashboard',
        category='reporting',
        read_only=True,
        concurrent_safe=True,
        timeout_s=30,
        max_output_chars=10000,
        risk_action='read',
        target_type='report',
        evidence_policy='dashboard',
        progress_policy='none',
        degradation_class='read_only',
        needs_validation=False,
        can_modify_state=False,
    ),
    'build_audit_summary': _spec(
        'build_audit_summary',
        category='reporting',
        read_only=True,
        concurrent_safe=True,
        timeout_s=15,
        risk_action='read',
        target_type='report',
        evidence_policy='audit',
        progress_policy='none',
        degradation_class='read_only',
        needs_validation=False,
        can_modify_state=False,
    ),
    'build_real_task_audit_summary': _spec(
        'build_real_task_audit_summary',
        category='reporting',
        read_only=True,
        concurrent_safe=True,
        timeout_s=15,
        risk_action='read',
        target_type='report',
        evidence_policy='audit',
        progress_policy='none',
        degradation_class='read_only',
        needs_validation=False,
        can_modify_state=False,
    ),
    'read_project_context': _spec(
        'read_project_context',
        category='context',
        read_only=True,
        concurrent_safe=True,
        timeout_s=15,
        risk_action='read',
        target_type='context',
        evidence_policy='context',
        progress_policy='none',
        degradation_class='read_only',
        needs_validation=False,
        can_modify_state=False,
    ),
    'retrieve_context': _spec(
        'retrieve_context',
        category='context',
        read_only=True,
        concurrent_safe=True,
        timeout_s=15,
        risk_action='read',
        target_type='context',
        evidence_policy='context',
        progress_policy='none',
        degradation_class='read_only',
        needs_validation=False,
        can_modify_state=False,
    ),
    'decide_next_task_v2': _spec(
        'decide_next_task_v2',
        category='scheduling',
        read_only=True,
        concurrent_safe=True,
        timeout_s=15,
        risk_action='read',
        target_type='state',
        evidence_policy='decision',
        progress_policy='derived',
        degradation_class='read_only',
        needs_validation=False,
        can_modify_state=False,
    ),
    'update_task_lifecycle': _spec(
        'update_task_lifecycle',
        category='state',
        read_only=False,
        concurrent_safe=False,
        timeout_s=15,
        risk_action='write-state',
        target_type='state',
        evidence_policy='state_change',
        progress_policy='state_write',
        degradation_class='state_write',
        needs_validation=True,
        can_modify_state=True,
    ),
    'update_task_state': _spec(
        'update_task_state',
        category='state',
        read_only=False,
        concurrent_safe=False,
        timeout_s=15,
        risk_action='write-state',
        target_type='state',
        evidence_policy='state_change',
        progress_policy='state_write',
        degradation_class='state_write',
        needs_validation=True,
        can_modify_state=True,
    ),
    'write_state_store': _spec(
        'write_state_store',
        category='state',
        read_only=False,
        concurrent_safe=False,
        timeout_s=15,
        risk_action='write-state',
        target_type='state',
        evidence_policy='state_change',
        progress_policy='state_write',
        degradation_class='state_write',
        needs_validation=True,
        can_modify_state=True,
    ),
    'run_task_supervision': _spec(
        'run_task_supervision',
        category='supervision',
        read_only=False,
        concurrent_safe=False,
        timeout_s=30,
        risk_action='write-state',
        target_type='state',
        evidence_policy='supervision',
        progress_policy='supervision',
        degradation_class='supervision',
        needs_validation=False,
        can_modify_state=True,
    ),
    'emit_heartbeat': _spec(
        'emit_heartbeat',
        category='supervision',
        read_only=False,
        concurrent_safe=False,
        timeout_s=15,
        risk_action='write-state',
        target_type='state',
        evidence_policy='heartbeat',
        progress_policy='heartbeat',
        degradation_class='supervision',
        needs_validation=False,
        can_modify_state=True,
    ),
    'write_handoff_state': _spec(
        'write_handoff_state',
        category='handoff',
        read_only=False,
        concurrent_safe=False,
        timeout_s=15,
        risk_action='write-state',
        target_type='state',
        evidence_policy='handoff',
        progress_policy='handoff',
        degradation_class='handoff',
        needs_validation=False,
        can_modify_state=True,
    ),
    'ingest_real_task': _spec(
        'ingest_real_task',
        category='state',
        read_only=False,
        concurrent_safe=False,
        timeout_s=30,
        risk_action='write-state',
        target_type='state',
        evidence_policy='ingest',
        progress_policy='ingest',
        degradation_class='state_write',
        needs_validation=True,
        can_modify_state=True,
    ),
    'close_task_runtime': _spec(
        'close_task_runtime',
        category='state',
        read_only=False,
        concurrent_safe=False,
        timeout_s=30,
        risk_action='write-state',
        target_type='state',
        evidence_policy='closure',
        progress_policy='closure',
        degradation_class='state_write',
        needs_validation=True,
        can_modify_state=True,
    ),
    'progress_task_runtime': _spec(
        'progress_task_runtime',
        category='state',
        read_only=False,
        concurrent_safe=False,
        timeout_s=60,
        risk_action='write-state',
        target_type='state',
        evidence_policy='progress',
        progress_policy='progress',
        degradation_class='state_write',
        needs_validation=True,
        can_modify_state=True,
    ),
    'safe_write': _spec(
        'safe_write',
        category='docs',
        read_only=False,
        concurrent_safe=False,
        timeout_s=10,
        risk_action='write-doc',
        target_type='document',
        evidence_policy='doc',
        progress_policy='doc_write',
        degradation_class='doc_write',
        needs_validation=False,
        can_modify_state=False,
    ),
    'log_event': _spec(
        'log_event',
        category='logs',
        read_only=False,
        concurrent_safe=True,
        timeout_s=5,
        risk_action='write-doc',
        target_type='document',
        evidence_policy='log',
        progress_policy='log_write',
        degradation_class='doc_write',
        needs_validation=False,
        can_modify_state=False,
    ),
    'check_delivery_completeness': _spec(
        'check_delivery_completeness',
        category='checks',
        read_only=True,
        concurrent_safe=True,
        timeout_s=15,
        risk_action='read',
        target_type='report',
        evidence_policy='delivery',
        progress_policy='none',
        degradation_class='read_only',
        needs_validation=False,
        can_modify_state=False,
    ),
    'check_state_view_consistency': _spec(
        'check_state_view_consistency',
        category='checks',
        read_only=True,
        concurrent_safe=True,
        timeout_s=15,
        risk_action='read',
        target_type='report',
        evidence_policy='consistency',
        progress_policy='none',
        degradation_class='read_only',
        needs_validation=False,
        can_modify_state=False,
    ),
    'check_risk_level': _spec(
        'check_risk_level',
        category='checks',
        read_only=True,
        concurrent_safe=True,
        timeout_s=15,
        risk_action='read',
        target_type='report',
        evidence_policy='risk',
        progress_policy='none',
        degradation_class='read_only',
        needs_validation=False,
        can_modify_state=False,
    ),
    'check_risk_policy_consistency': _spec(
        'check_risk_policy_consistency',
        category='checks',
        read_only=True,
        concurrent_safe=True,
        timeout_s=15,
        risk_action='read',
        target_type='report',
        evidence_policy='risk',
        progress_policy='none',
        degradation_class='read_only',
        needs_validation=False,
        can_modify_state=False,
    ),
    'check_next_task_consistency': _spec(
        'check_next_task_consistency',
        category='checks',
        read_only=True,
        concurrent_safe=True,
        timeout_s=15,
        risk_action='read',
        target_type='report',
        evidence_policy='next_task',
        progress_policy='none',
        degradation_class='read_only',
        needs_validation=False,
        can_modify_state=False,
    ),
    'check_retrieval_priority': _spec(
        'check_retrieval_priority',
        category='checks',
        read_only=True,
        concurrent_safe=True,
        timeout_s=15,
        risk_action='read',
        target_type='report',
        evidence_policy='context',
        progress_policy='none',
        degradation_class='read_only',
        needs_validation=False,
        can_modify_state=False,
    ),
    'system_healthcheck': _spec(
        'system_healthcheck',
        category='checks',
        read_only=True,
        concurrent_safe=True,
        timeout_s=30,
        risk_action='read',
        target_type='report',
        evidence_policy='health',
        progress_policy='none',
        degradation_class='read_only',
        needs_validation=False,
        can_modify_state=False,
    ),
    'delivery_gate': _spec(
        'delivery_gate',
        category='checks',
        read_only=True,
        concurrent_safe=True,
        timeout_s=15,
        risk_action='read',
        target_type='report',
        evidence_policy='delivery',
        progress_policy='none',
        degradation_class='read_only',
        needs_validation=False,
        can_modify_state=False,
    ),
    'progress_reply_gate': _spec(
        'progress_reply_gate',
        category='checks',
        read_only=True,
        concurrent_safe=True,
        timeout_s=5,
        risk_action='read',
        target_type='report',
        evidence_policy='progress',
        progress_policy='none',
        degradation_class='read_only',
        needs_validation=False,
        can_modify_state=False,
    ),
    'resume_task': _spec(
        'resume_task',
        category='resume',
        read_only=False,
        concurrent_safe=False,
        timeout_s=30,
        risk_action='write-state',
        target_type='state',
        evidence_policy='resume',
        progress_policy='resume',
        degradation_class='state_write',
        needs_validation=False,
        can_modify_state=True,
    ),
    'resume_real_task': _spec(
        'resume_real_task',
        category='resume',
        read_only=False,
        concurrent_safe=False,
        timeout_s=30,
        risk_action='write-state',
        target_type='state',
        evidence_policy='resume',
        progress_policy='resume',
        degradation_class='state_write',
        needs_validation=False,
        can_modify_state=True,
    ),
    'resume_many_tasks': _spec(
        'resume_many_tasks',
        category='resume',
        read_only=False,
        concurrent_safe=False,
        timeout_s=60,
        risk_action='write-state',
        target_type='state',
        evidence_policy='resume',
        progress_policy='resume',
        degradation_class='state_write',
        needs_validation=False,
        can_modify_state=True,
    ),
    'evaluate_failure_control': _spec(
        'evaluate_failure_control',
        category='analysis',
        read_only=False,
        concurrent_safe=False,
        timeout_s=10,
        risk_action='write-state',
        target_type='state',
        evidence_policy='analysis',
        progress_policy='analysis',
        degradation_class='analysis',
        needs_validation=False,
        can_modify_state=True,
    ),
    'evaluate_risk_policy': _spec(
        'evaluate_risk_policy',
        category='analysis',
        read_only=True,
        concurrent_safe=True,
        timeout_s=10,
        risk_action='read',
        target_type='report',
        evidence_policy='risk',
        progress_policy='none',
        degradation_class='read_only',
        needs_validation=False,
        can_modify_state=False,
    ),
    'evaluate_retry_reorder': _spec(
        'evaluate_retry_reorder',
        category='analysis',
        read_only=False,
        concurrent_safe=False,
        timeout_s=10,
        risk_action='write-state',
        target_type='state',
        evidence_policy='analysis',
        progress_policy='analysis',
        degradation_class='analysis',
        needs_validation=False,
        can_modify_state=True,
    ),
}


def get_action_spec(script_name: str) -> ActionSpec:
    name = normalize_action_name(script_name)
    spec = ACTION_SPECS.get(name)
    if spec is None:
        return replace(DEFAULT_ACTION_SPEC, name=name, script_name=name)
    return spec


def get_action_meta(script_name: str) -> dict:
    spec = get_action_spec(script_name)
    return {
        'name': spec.name,
        'script_name': spec.script_name,
        'category': spec.category,
        'read_only': spec.read_only,
        'concurrent_safe': spec.concurrent_safe,
        'timeout': spec.timeout_s,
        'max_result_chars': spec.max_output_chars,
        'risk_action': spec.risk_action,
        'target_type': spec.target_type,
        'evidence_policy': spec.evidence_policy,
        'progress_policy': spec.progress_policy,
        'degradation_class': spec.degradation_class,
        'needs_validation': spec.needs_validation,
        'can_modify_state': spec.can_modify_state,
    }


def is_registered_action(script_name: str) -> bool:
    return normalize_action_name(script_name) in ACTION_SPECS


def list_concurrent_safe_actions() -> list[str]:
    return [
        name
        for name, spec in ACTION_SPECS.items()
        if spec.read_only and spec.concurrent_safe
    ]


def list_state_modifying_actions() -> list[str]:
    return [
        name
        for name, spec in ACTION_SPECS.items()
        if spec.can_modify_state
    ]
